//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Streaming.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.mewsick.Middleware;

public class Morceau extends com.zeroc.Ice.Value
{
    public Morceau()
    {
        this.titre = "";
        this.artiste = "";
        this.album = "";
        this.localisation = "";
    }

    public Morceau(String titre, String artiste, String album, String localisation)
    {
        this.titre = titre;
        this.artiste = artiste;
        this.album = album;
        this.localisation = localisation;
    }

    public String titre;

    public String artiste;

    public String album;

    public String localisation;

    public Morceau clone()
    {
        return (Morceau)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Middleware::Morceau";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1619265776L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(titre);
        ostr_.writeString(artiste);
        ostr_.writeString(album);
        ostr_.writeString(localisation);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        titre = istr_.readString();
        artiste = istr_.readString();
        album = istr_.readString();
        localisation = istr_.readString();
        istr_.endSlice();
    }
}
